VERSION="2.2.1"
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
  "GAYCCWKECNGDRHYU3UTREBD2XLC3CUQN6FV22TKM4WCQER3IWR7TF5CY",
  "GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD",
  "GBXN3ONPRC4TX4CQFYAOCMSFCZSUTR2U3GJWCVQ27Z2OKFWTW42HE2ZK",
  "GANIPXJRN6TSH7354OGYH4XS5P6L72MFTZ32BGHIOB2H6JD3MLJCPUXQ",
  "GD3ACA6FPINT4FDAA3YKR5M5OCDQ5NOQ24VW4TUMGKFENOLYO37UOD7Q",
  "GAGG42ACMQ3454R7GB6JUAKU6OPT4EXPW4QWYKEKBVYDQJC3ELGW74AX",
  "GBJEIA7DSCBQS37XH6NYBVDVF6DDYM33DJRP6PIQQQNBQLSHHCUKVIDS",
  "GDID3VFXZ6BZXIBVCQXUYVUEOVPZHNBQUGDNZ43GIYD2F4QM2YBO4MF5",
  "GADTKVHGJNR5HFCWNKQRMJQ44CXDHETPAFPG7XVG4WPTEQFWTLDADXMS"
]

[DOCUMENTATION]
ORG_NAME="LibreXLM"
ORG_DESCRIPTION="An autonomous experimental trading token on the Stellar Network"
ORG_URL="https://librexlm.github.io"
ORG_LOGO="https://librexlm.github.io/img/LIBRE_PNG.jpg"
ORG_OFFICIAL_EMAIL="librexlm@gmail.com"

[[PRINCIPALS]]
name="LIBRE"
email="librexlm@gmail.com"
github="LibreXLM"

[[CURRENCIES]]
code="LIBRE"
status="live"
issuer="GAYCCWKECNGDRHYU3UTREBD2XLC3CUQN6FV22TKM4WCQER3IWR7TF5CY"
display_decimals=7
name="LIBRE"
desc="The core token of the LibreTradingEcosystem. An autonomous experimental asset for studying trading dynamics in Stellar liquidity pools."
conditions="LIBRE is an experimental token. No guarantees, no intrinsic value, not an investment product."
image="https://librexlm.github.io/img/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=false
anchor_asset="LIBRE"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="ReverseLibre"
status="live"
issuer="GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD"
display_decimals=7
name="ReverseLibre"
desc="A counter-experimental token within the LibreTradingEcosystem."
conditions="Purely experimental asset. No claim to value or stability."
image="https://librexlm.github.io/img/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=false
anchor_asset="REVERSELIBRE"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="MOONSHOT"
status="live"
issuer="GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD"
display_decimals=7
name="Moonshot"
desc="Speculative experimental token created in the Libre ecosystem."
conditions="Not a financial product. Created for community experimentation only."
image="https://librexlm.github.io/img/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=false
anchor_asset="MOONSHOT"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="ANUSINU"
status="live"
issuer="GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD"
display_decimals=7
name="Anus Inu"
desc="A meme-inspired asset circulating within the LibreTradingEcosystem."
conditions="Has no financial or intrinsic value. Exists purely as a cultural and community-driven asset."
image="https://librexlm.github.io/img/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=false
anchor_asset="ANUSINU"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="SHITCOIN"
status="live"
issuer="GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD"
display_decimals=7
name="Shitcoin"
desc="Parody asset to highlight risks of unregulated token creation."
conditions="Carries no actual value, not an investment, purely humorous in intent."
image="https://librexlm.github.io/img/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=false
anchor_asset="SHITCOIN"
anchor_asset_type="crypto"

