VERSION="2.2.1"
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
  "GAYCCWKECNGDRHYU3UTREBD2XLC3CUQN6FV22TKM4WCQER3IWR7TF5CY",
  "GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD",
  "GBXN3ONPRC4TX4CQFYAOCMSFCZSUTR2U3GJWCVQ27Z2OKFWTW42HE2ZK",
  "GANIPXJRN6TSH7354OGYH4XS5P6L72MFTZ32BGHIOB2H6JD3MLJCPUXQ",
  "GD3ACA6FPINT4FDAA3YKR5M5OCDQ5NOQ24VW4TUMGKFENOLYO37UOD7Q",
  "GAGG42ACMQ3454R7GB6JUAKU6OPT4EXPW4QWYKEKBVYDQJC3ELGW74AX",
  "GBJEIA7DSCBQS37XH6NYBVDVF6DDYM33DJRP6PIQQQNBQLSHHCUKVIDS",
  "GDID3VFXZ6BZXIBVCQXUYVUEOVPZHNBQUGDNZ43GIYD2F4QM2YBO4MF5",
  "GADTKVHGJNR5HFCWNKQRMJQ44CXDHETPAFPG7XVG4WPTEQFWTLDADXMS"
]

[DOCUMENTATION]
ORG_NAME="LibreXLM"
ORG_DESCRIPTION="An autonomous experimental trading token on the Stellar Network"
ORG_URL="https://librexlm.github.io"
ORG_LOGO="https://librexlm.github.io/img/LIBRE_PNG.jpg"
ORG_OFFICIAL_EMAIL="librexlm@gmail.com"

[[PRINCIPALS]]
name="LIBRE"
email="librexlm@gmail.com"
github="LibreXLM"

[[CURRENCIES]]
code="LIBRE"
status="live"
issuer="GAYCCWKECNGDRHYU3UTREBD2XLC3CUQN6FV22TKM4WCQER3IWR7TF5CY"
display_decimals=7
name="LIBRE"
desc="The core token of the LibreTradingEcosystem. An autonomous experimental asset for studying trading dynamics in Stellar liquidity pools."
conditions="LIBRE is an experimental token. No guarantees, no intrinsic value, not an investment product."
image="https://librexlm.github.io/img/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=false
anchor_asset="LIBRE"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="ReverseLibre"
status="live"
issuer="GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD"
display_decimals=7
name="Reverse Libre"
desc="Counter-experimental token within the LibreTradingEcosystem."
conditions="Experimental token, not intended for speculation or financial use."
image="https://librexlm.github.io/img/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=false
anchor_asset="ReverseLibre"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="LibreVolume"
status="live"
issuer="GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD"
display_decimals=7
name="Libre Volume"
desc="Token representing volume dynamics in the Libre ecosystem."
conditions="Experimental token measuring liquidity volume. Not a financial product."
image="https://librexlm.github.io/img/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=true
anchor_asset="LibreVolume"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="yZOMB"
status="live"
issuer="GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD"
display_decimals=7
name="yZOMB"
desc="An experimental yield-style pool token in the Libre ecosystem."
conditions="Created to explore compounding pool mechanics. No intrinsic value."
image="https://librexlm.github.io/img/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=true
anchor_asset="yZOMB"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="yFRED"
status="live"
issuer="GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD"
display_decimals=7
name="yFRED"
desc="Experimental asset named yFRED within Libre ecosystem."
conditions="Experimental token without guarantees or backing."
image="https://librexlm.github.io/img/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=true
anchor_asset="yFRED"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="yLMT"
status="live"
issuer="GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD"
display_decimals=7
name="yLMT"
desc="Token exploring liquidity mining trends within the Libre ecosystem."
conditions="Experimental token for studying AMM and yield behavior."
image="https://librexlm.github.io/img/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=true
anchor_asset="yLMT"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="yLUMOS"
status="live"
issuer="GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD"
display_decimals=7
name="yLUMOS"
desc="Experimental token symbolizing 'light' in the Libre ecosystem."
conditions="Community experiment. Carries no financial rights."
image="https://librexlm.github.io/img/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=true
anchor_asset="yLUMOS"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="maxBREAD"
status="live"
issuer="GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD"
display_decimals=7
name="maxBREAD"
desc="Meme-style experimental token within Libre."
conditions="Exists purely for community experiment. No guarantees."
image="https://librexlm.github.io/img/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=true
anchor_asset="maxBREAD"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="200XLM"
status="live"
issuer="GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD"
display_decimals=7
name="200XLM"
desc="Experimental asset named after 200XLM, within Libre ecosystem."
conditions="Token has no direct backing by XLM. Purely experimental."
image="https://librexlm.github.io/img/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=true
anchor_asset="200XLM"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="yDWARF"
status="live"
issuer="GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD"
display_decimals=7
name="yDWARF"
desc="Experimental yield token yDWARF."
conditions="Libre ecosystem experiment. No real-world value."
image="https://librexlm.github.io/img/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=true
anchor_asset="yDWARF"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="100XLM"
status="live"
issuer="GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD"
display_decimals=7
name="100XLM"
desc="Experimental asset named after 100XLM, within Libre ecosystem."
conditions="Token has no direct backing by XLM. Purely experimental."
image="https://librexlm.github.io/img/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=true
anchor_asset="100XLM"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="not100XLM"
status="live"
issuer="GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD"
display_decimals=7
name="not100XLM"
desc="Parody token 'not100XLM' within Libre ecosystem."
conditions="Does not represent or redeem any XLM. Purely experimental."
image="https://librexlm.github.io/img/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=true
anchor_asset="not100XLM"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="yTATT"
status="live"
issuer="GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD"
display_decimals=7
name="yTATT"
desc="Experimental yield-style token yTATT."
conditions="Libre ecosystem token. No value guaranteed."
image="https://librexlm.github.io/img/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=true
anchor_asset="yTATT"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="yBBOI"
status="live"
issuer="GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD"
display_decimals=7
name="yBBOI"
desc="Experimental yield-style token yBBOI."
conditions="Libre ecosystem token. No value guaranteed."
image="https://librexlm.github.io/img/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=true
anchor_asset="yBBOI"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="yGRACE"
status="live"
issuer="GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD"
display_decimals=7
name="yGRACE"
desc="Experimental yield-style token yGRACE."
conditions="Libre ecosystem token. No value guaranteed."
image="https://librexlm.github.io/img/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=true
anchor_asset="yGRACE"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="Libre420"
status="live"
issuer="GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD"
display_decimals=7
name="Libre420"
desc="Experimental meme token Libre420."
conditions="Community fun token. Purely symbolic."
image="https://librexlm.github.io/img/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=true
anchor_asset="Libre420"
anchor_asset_type="crypto"
